Update debupdate

diff --git a/debupdate b/debupdate
--- a/debupdate
+++ b/debupdate
@@ -99,12 +99,39 @@ hours=$(( (time_difference % 86400) / 3600 ))
 minutes=$(( (time_difference % 3600) / 60 ))
 # Get the running kernel version
 running_kernel=$(uname -r)
+
+
+# Input version string
+rversion=$(running_kernel)
+
+# Extract major version using regular expression
+if [[ $rversion =~ ^([0-9]+\.[0-9]+\.[0-9]+).* ]]; then
+  rversion="${BASH_REMATCH[1]}"
+else
+  echo "Invalid version format"
+  exit 1
+fi
+echo "Major version: $rversion"
+running_kernel=$(rversion)
+
 # Get the installed kernel version
 #installed_kernel=$(rpm -q kernel --last | awk 'NR==1{print $1}')
 #installed_kernel=$(ls /boot/vmlinuz-* | awk -F'-' '{print $2}')
 #installed_kernel=$(dpkg -l | grep linux- | awk '{print $2}' | awk -F'-' '{print $4}')
 installed_kernel=$(dpkg --list | grep "linux-image" | awk '{print $3}' | awk -F'-' '{print $1}' | sort -V | tail -n1)
 
+# Input version string
+iversion=$(installed_kernel)
+
+# Extract major version using regular expression
+if [[ $iversion =~ ^([0-9]+\.[0-9]+\.[0-9]+).* ]]; then
+  iversion="${BASH_REMATCH[1]}"
+else
+  echo "Invalid version format"
+  exit 1
+fi
+echo "Major version: $iversion"
+installed_kernel=$(iversion)
 
 if [[ $running_kernel != $installed_kernel ]]; then
   echo "pick $USER@$HOSTNAME ($HOST_IP)" &&  uname -a
